networks:
  ansible-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  ansible-control:
    depends_on:
      - ansible-node1
      - ansible-node2
    build:
      context: .
      dockerfile: ControlDockerfile
    ports:
      - 2201:22
      - 8001:80
      - 1443:443
    volumes:
      - ./:/home/ansible/ansible
    networks:
      ansible-net:
        ipv4_address: 172.20.0.2
        aliases:
          - ansible-control
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.00'
    command: >
      /bin/sh -c '
      apk update &&
      apk add --no-cache sshpass &&
      su - ansible -c "sshpass -p \"ansible\" ssh-copy-id -o StrictHostKeyChecking=no -i /home/ansible/.ssh/id_rsa.pub ansible@172.20.0.3" &&
      su - ansible -c "sshpass -p \"ansible\" ssh-copy-id -o StrictHostKeyChecking=no -i /home/ansible/.ssh/id_rsa.pub ansible@172.20.0.4" &&
      cp /home/ansible/ansible/ansible.cfg /home/ansible/ansible.cfg &&
      /usr/sbin/sshd -D'

  ansible-node1:
    build:
      context: .
      dockerfile: ManagedDockerfile
    ports:
      - 2202:22
      - 8002:80
      - 2443:443
    networks:
      ansible-net:
        ipv4_address: 172.20.0.3
        aliases:
          - ansible-node1
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.50'

  ansible-node2:
    build:
      context: .
      dockerfile: ManagedDockerfile
    ports:
      - 2203:22
      - 8003:80
      - 3443:443
    networks:
      ansible-net:
        ipv4_address: 172.20.0.4
        aliases:
          - ansible-node2
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.50'
