---

- name: Deploy static webpage
  hosts: managed_nodes
  become: true
  vars:
    temp_directory: /tmp

  tasks:
    - name: Gather the package facts
      package_facts:
        manager: apk

    - name: Download webpage
      ansible.builtin.include_tasks: ./deploy_website/download_webpage.yml
      vars:
        temp_dir: "{{ temp_directory }}"
        zip_file: https://github.com/hhlitval/simple-portfolio-template/archive/refs/heads/main.zip
        
    - name: Extract webpage
      ansible.builtin.include_tasks: ./deploy_website/extract_webpage.yml
      vars:
        temp_dir: "{{ temp_directory }}"
        packages: "{{ ansible_facts.packages }}"
        webpage_location: /var/www/custom-webpage/

    - name: Set Nginx configuration
      ansible.builtin.include_tasks: ./deploy_website/config_nginx.yml
      vars:
        packages: "{{ ansible_facts.packages }}"