---
- import_playbook: ensure_openrc.yml
    
- name: Install and configure Nginx
  hosts: managed_nodes_dev
  become: yes
  tasks:
    - name: Install nginx package
      apk:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes